from dataclasses import dataclass

HEADER = """silq// AUTO-GENERATED by Silq Sonata
// NOTE: This is Silq-like pseudocode intended for conceptual verification.
"""

FOOTER_MAIN = """
def main(): () {
    out := run_story();
    print(out);
}
"""

ALLOWED_TOKENS = {
    "fresh(", "h(", "rz(", "cnot(", "measure(", "return", "def ", "print(", "==", "->",
    ":", "{", "}", ")", "(", ",", ";"
}

@dataclass
class OrchestratorConfig:
    auto_uncompute: bool = True
    verify_with: str = "z3"

class Orchestra:
    def __init__(self, cfg: OrchestratorConfig = OrchestratorConfig()):
        self.cfg = cfg

    def compile_score(self, score: str) -> str:
        body = score.strip()
        unsafe = []
        for word in body.split():
            w = word.strip()
            if any(tok in w for tok in ALLOWED_TOKENS):
                continue
            if w.startswith("//") or w.endswith(")") or w.endswith("};") or w.endswith("}"):
                continue
            if all(ch.isalnum() or ch in "_:;,.(){}[]/\"'=+-*" for ch in w):
                continue
            unsafe.append(w)

        if unsafe:
            body = "// [WARN] Unvetted tokens detected, review manually.\n" + body

        meta = f"// auto_uncompute={self.cfg.auto_uncompute}, verify_with={self.cfg.verify_with}\n"
        add_main = ("def main" not in body) and ("def run_story" in body)
        return HEADER + meta + body + ("\n" + FOOTER_MAIN if add_main else "")
